#  @author: Marco Giberna
#  @email: marco.giberna@studenti.units.it
#  @email: marcogiberna@gmail.com
global_costmap:
  global_frame: map
  robot_base_frame: Archimede_base_link
  update_frequency: 5.0
  # static_map: true # not longer used - determines whether or not the costmap should initialize itself based on a map served by the map_server. If you aren't using an existing map or map server, set the static_map parameter to false.
  # rolling_window: true
  always_send_full_costmap: true
  width: 250
  height: 250
  origin_x: -125
  origin_y: -125
  resolution: 0.05
  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}