#  @author: Marco Giberna
#  @email: marco.giberna@studenti.units.it
#  @email: marcogiberna@gmail.com
local_costmap:
  global_frame: map
  robot_base_frame: Archimede_foot_print
  update_frequency: 5.0
  publish_frequency: 2.0 # the rate, in Hz, at which the costmap will publish visualization information
  #static_map: false # determines whether or not the costmap should initialize itself based on a map served by the map_server. 
  rolling_window: true # true means that the costmap will remain centered around the robot as the robot moves through the world
  width: 6.0
  height: 6.0
  origin_x: -3.0
  origin_y: -3.0
  resolution: 0.05
  transform_tolerance: 0.5
  plugins:
    - {name: voxel_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}