#  @author: Marco Giberna
#  @email: marco.giberna@studenti.units.it
#  @email: marcogiberna@gmail.com
local_costmap:
  global_frame: map
  robot_base_frame: Archimede_foot_print
  update_frequency: 5.0
  publish_frequency: 2.0 # the rate, in Hz, at which the costmap will publish visualization information
  #static_map: false # determines whether or not the costmap should initialize itself based on a map served by the map_server. 
  rolling_window: true # true means that the costmap will remain centered around the robot as the robot moves through the world
  width: 6.0
  height: 6.0
  resolution: 0.05
  # origin_x: -4
  # origin_y: -4
  # transform_tolerance: 0.5 
  # plugins:
  #   - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
  #   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}

  # plugins: ["obstacle_layer", "inflation_layer"]
  # inflation_layer:
  #   plugin: "costmap_2d::InflationLayer"
  #   cost_scaling_factor: 3.0
  #   inflation_radius: 0.1
  # obstacle_layer:
  #   plugin: "costmap_2d::ObstacleLayer"
  #   enabled: True
  #   observation_sources: pointcloud
  #   pointcloud:
  #     topic:  /Archimede/d435i_camera/depth/color/points
  #     max_obstacle_height: 10.0
  #     min_obstacle_height: 0.2
  #     obstacle_max_range: 2.5
  #     obstacle_min_range: 0.0
  #     raytrace_max_range: 10.0
  #     raytrace_min_range: 0.0
  #     clearing: True
  #     marking: True
  #     data_type: "PointCloud2"